### ISSUE TITLE
how can get .jar

### ISSUE THREAD

**Issue by 2216ChoiwooYoung** [AgoraIO/Agora-Android-Tutorial-1to1#10]
I got into  Agora.io SDK but I can't download .jar file
and when I was "start" in android, 

error like this
Error:A problem was found with the configuration of task ':app:prepareOpenLiveAndroidMasterLibvideoprpUnspecifiedLibrary'.
> File 'C:\Users\wychoi\Downloads\OpenLive-Android-master\libvideoprp\videoprp.aar' specified for property 'bundle' does not exist.

**Comment by guohai** [comment]
You can download all the SDKs at https://www.agora.io/en/download/

videoprp.aar belongs to Agora image enhancement SDK
