### ISSUE TITLE
Didn't find class "io.agora.rtc.audio.AudioManagerAndroid"

### ISSUE THREAD

**Issue by quyvv01581** [AgoraIO/Agora-Android-Tutorial-1to1#11]
I got this error when build release, but everything working fine when i build debug.
I've looking at https://dev.agora.io/en/question/1599 and change sdk version but still got this error. Please help.

**Comment by guohai** [comment]
Maybe you should keep all the classes unobfuscated

-keep class io.agora.** { *; }
