### ISSUE TITLE
Incorrect location specified for native libs in build.gradle

### ISSUE THREAD

**Issue by ImMathanR** [AgoraIO/Agora-Android-Tutorial-1to1#5]
Change the path of the native libraries in build.gradle.
[
Change this line
](https://github.com/AgoraIO/Agora-Android-Tutorial-1to1/blob/master/app/build.gradle#L24)

` jniLibs.srcDirs = ['src/main/libs']`
to 
` jniLibs.srcDirs = ['src/main/jniLibs']`

**Comment by guohai** [comment]
Thanks for you feedback, but for legacy reasons, we have some internal tools that would check and verify the source code, it only support 'src/main/libs'. And 'src/main/libs' is widely-recommended in gradle.

**Comment by guohai** [comment]
@ImMathanR 

Now we have changed the path of native library path to jniLibs, close this issue.
