### ISSUE TITLE
NDK problem when convert the project into library and try to import it as a module

### ISSUE THREAD

**Issue by Vullett** [AgoraIO/Agora-Android-Tutorial-1to1#6]
Dear Support;
kindly need your help as i try to incluide or import the video sample as a library in another project after adding my api key.
it didn't continue on build process and give me the following error on NDK and as attached on picture:

ifndef prebuilt
$(call __ndk_info,ERROR:$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES points to a missing file)
$(call __ndk_info,Check that $(prebuilt_path) exists, or that its path is correct)
$(call __ndk_error,Aborting)
endif

Error:(45) *** Android NDK: Aborting . Stop.
Error:(45) *** Android NDK: Aborting . Stop.
C:\Users\mahmoud.mosaad\AppData\Local\Android\sdk\ndk-bundle\build\core\prebuilt-library.mk

Error:A problem occurred configuring project ':agora'.
> executing external native build for ndkBuild D:\vullettProjects\Test2\agora\src\main\cpp\Android.mk

![ndk](https://cloud.githubusercontent.com/assets/18436899/25808344/1cbb329c-340a-11e7-9416-aaf596186c94.PNG)

**Comment by guohai** [comment]
Check your agora\src\main\cpp\Android.mk and find if the specified file really existing
