### ISSUE TITLE
 dlopen failed: /data/app/io.agora.tutorials1v1vcall-1/lib/x86/libagora-rtc-sdk-jni.so: has text relocations

### ISSUE THREAD

**Issue by naguchennai** [AgoraIO/Agora-Android-Tutorial-1to1#7]
dlopen failed: /data/app/io.agora.tutorials1v1vcall-1/lib/x86/libagora-rtc-sdk-jni.so: has text relocations

**Comment by guohai** [comment]
@naguchennai Can you provide more device info?

**Comment by naguchennai** [comment]
Device info? first explain this..

"Unzip the downloaded SDK package and copy the "*.jar" to "app/libs", "arm64-v8a"/"x86"/"armeabi-v7a" to "app/src/main/libs"

really hard text ... i dont know which file where i put? try explain clearly..

**Comment by guohai** [comment]
device info means on which device this issue happens? manufacturer/model/brand name?

**Comment by 2hamed** [comment]
Hey,
I'm having the same problem using Android Emulator.

**Comment by naguchennai** [comment]
its working fine with real device

**Comment by asabadyr** [comment]
Any chance to make this run in Emulator? 
Also face this issue

**Comment by achirun** [comment]
I've got next error: Java.Lang.UnsatisfiedLinkError: dlopen failed: /lib/x86/libagora-rtc-sdk-jni.so has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

**Comment by jeffreyyoung** [comment]
Is it possible to run this library in an emulator?

**Comment by achirun** [comment]
@jeffreyyoung Yes, you can run it on an emulator with android target before Android 6.0.
